language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: gY/N/rukYb9OHUzDkVT6chp9gYSm2YFs07LoMAN87tN1DHPXNsdmdjS3lPLLBnmkefRbpivV83JprrliGN5WRwLWFpuJ/f3gM5HdOX76Fv5PKgjIP09/P2TYMcIAYNNBFJRy37kTANHNgk9Ms+aBEqEr7xUT1Rw7KLlhbkTJVpJK3pmNE6wb3IHaurwtscBhOrO8RtirYPXIrkv29h8ozOvnTtaTdAb6KXLfa9mYl7tlCSxe4Rh4i/YLf4Rjg9FKlnRLhgwIopw2MX9/+rwt94B+Qo/31TMzvx34VvYAvRdv+zu6gkWMNvm7TmyVY6Ne1sY1rO5NbGXbt2EeQjyWeyd6F3MI2eBtGZ99c8PCPVvZoLHK9H45z3tGqrA/qeiv3Xdj8k7O6b7wxvpBs1qNMA355KZ2JzhadvfkpVU3vkEWwKU0LVsFSQrpDqBpdGIz5B002GtsHB5y72l5J0XbNYmZEAqdVNZRp1Z//skZCvf6cepUbRHikCVLPgP34A6bV/opADw73b/uMGuxm3g0PNEVaMHvAS5KxtEdtCyC7xho4n8fYtxt9JKpYDSgB3Z20dyL4y8AiUm7Vp3MYm00G4dhUAmtwD3gKLl8DrHVHqNsmpvU2okiy93cw/SRrcEASSsTtn+lNtgpzRJW2WGtVOCv3YqK97Zovov6ld+27WU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
